#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091,SC2154

source /scripts/common
# -----------------------------------------------------------------------------------
# Copyright 2025 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-api2sbs/blob/main/LICENSE
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#

if [[ -f /.VERSION ]]; then
  "${s6wrap[@]}" echo "API2SBS Version: $(cat /.VERSION)"
fi