#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154
source /scripts/common

STATS_INTERVAL="${STATS_INTERVAL:-300}"

if chk_disabled "$STATS_INTERVAL"; then 
  "${s6wrap[@]}" echo "Stats collection disabled."
  exec sleep infinity
fi

# wait until there are messages in the cache
while ! compgen -G "/tmp/sbs_msgs_cache.*" >/dev/null 2>/dev/null; do
  sleep 1  
done

"${s6wrap[@]}" echo "Stats started - will be showing statistics every $STATS_INTERVAL seconds"

declare -A total_msgs

while :; do
  sleep "$STATS_INTERVAL"
  for f in /tmp/sbs_msgs_cache.*; do
    msgs="$(wc -l < "$f")"
    truncate -s 0 "$f"
    total_msgs["$f"]="$(( total_msgs["$f"] + msgs ))"
    "${s6wrap[@]}" echo "LAT,LON,DIST=${f#*.}: msgs in previous $STATS_INTERVAL secs: $msgs messages; since container start: ${total_msgs["$f"]}"
  done

done