#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154
source /scripts/common

STATS_INTERVAL="${STATS_INTERVAL:-60}"

# wait until there are messages in the cache
while ! compgen -G "/tmp/sbs_msg_cache.*" >/dev/null 2>/dev/null; do
  sleep 1  
done

"${s6wrap[@]}" echo "Stats started - will be showing statistics every $STATS_INTERVAL seconds"

while :; do
  sleep "$STATS_INTERVAL"
  for f in /tmp/sbs_msg_cache.*; do
    "${s6wrap[@]}" echo "In the last minute, Number of messages received for coordinates LAT,LON,DIST ${f#*.}: $(cat $f | wc -l)"
    truncate -s 0 "$f"
  done

done